[package]
name = "fts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
csv = "1.2.2"
glob = "0.3.1"
regex = "1.9.1"
